export const SEARCH_MARKERS_REQUEST = 'map/SEARCH_MARKERS_REQUEST'
export const SEARCH_MARKERS_DONE = 'map/SEARCH_MARKERS_DONE'
export const SEARCH_REQUEST = 'map/SEARCH_REQUEST'
export const SEARCH_DONE = 'map/SEARCH_DONE'
